name: betonica_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - stacks=2.68
  - fastqc=0.12.1
  - multiqc=1.28
  - vcftools=0.1.16
  - plink=1.90b7.7
  - bcftools=1.21
  - admixture=1.3.0
  - fineradstructure=0.3.2r109
  - iqtree=2.4.0
  - biopython=1.85
  - bowtie2=2.5.4
  - seqtk=1.5
  - pandas=2.3.0
  - matplotlib=3.10.3
  - treemix=1.13
  - parallel=20250822
  - phylip=3.697
